### PR TITLE
Centralize configuration of pip/setuptools versions

### PR DESCRIPTION
**Pull request by bkabrda**
This PR creates a single file that defines used pip/setuptools versions used in all Linux and Windows images. Changing versions in this file will update all our buildimages.

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]
Looks good. This makes me think that I don't understand why we are keeping the py2 environment here yet. Do you know what do we use it for?

**Comment by bkabrda** [comment]
@mx-psi that's a good question. I don't know actually, I'll try to find out.

**Comment by bkabrda** [comment]
@mx-psi here: https://github.com/DataDog/datadog-agent/blob/main/.gitlab/source_test/linux.yml#L39

**Comment by mx-psi** [comment]
ah, right, for rtloader tests with Python 2. Makes sense, thanks!

**Pull request merged**
