### PR TITLE
Activate py3 env by default

### PR DESCRIPTION
**Pull request by albertvaka**
So we can call invoke/pip straight away.

### CODE REVIEW

**Comment by albertvaka** [comment]
I think the unit tests use python from the image itself. Eg: https://github.com/DataDog/datadog-agent/blob/master/.gitlab-ci.yml#L223

**Comment by olivielpeau** [comment]
oh, you're right 👍 Nevermind then.

FWIW, we used to have separate test vs. build images in the past, but it was a hassle to maintain both.

**Comment by KSerrania** [comment]
This breaks the ARM image at runtime as it does not ship `conda`, we should either have separate `entrypoint.sh`, change the ARM image to use anaconda, or change the x86_64 image to not use anaconda.

**Comment by albertvaka** [comment]
Fix: https://github.com/DataDog/datadog-agent-buildimages/pull/29

**Pull request merged**
